compile:
	g++ -std=c++17 -Wall -g -o ws tester_1.cpp settings.cpp book.cpp movie.cpp tvShow.cpp spellChecker.cpp collection.cpp

run:
	./ws	

playc:
	g++ -std=c++17 -Wall -g -o play play.cpp

playr:
	rm play